Add support for .strict table option in 3.37+
groue/GRDB.swift pull request #1288
Opened 2022-10-19 14:01 UTC by jcavar

Resolves https://github.com/groue/GRDB.swift/issues/1287

### Pull Request Checklist

- [x] CONTRIBUTING: You have read https://github.com/groue/GRDB.swift/blob/master/CONTRIBUTING.md
- [x] BRANCH: This pull request is submitted against the `development` branch.
- [x] DOCUMENTATION: Inline documentation has been updated.
- [ ] DOCUMENTATION: README.md or another dedicated guide has been updated.
- [x] TESTS: Changes are tested.
- [x] TESTS: The `make smokeTest` terminal command runs without failure.

2022-10-19 16:42 UTC, groue requested changes
Thank you @jcavar :-) This looks very good.

During the refactoring, one test was lost, and I think we should restore it.

2022-10-19 16:42 UTC, groue commented on Tests/GRDBTests/TableDefinitionTests.swift
> -            }
This test looks like it tests SQLite itself, and has little value.

Instead, let's say it tests that GRDB properly handles the `.strict` option, by enabling the side-effect that is intended by the user: SQLite throws an error when the application tries to insert a value with the wrong data type.

From this point of view, this test has a value. Would you please restore it in both `testStrictTableCreationOptionCustomAndCipher` and `testStrictTableCreationOption`?

2022-10-20 06:52 UTC, groue commented
I took the liberty to apply the necessary fixes. Also, the test is now skipped for SQLCipher 3.

2022-10-20 10:59 UTC, groue commented
OK, tests pass 👍 Thank you very much @jcavar, I'll prepare a release shortly.

2022-10-20 10:59 UTC, groue approved these changes

2022-10-20 11:00 UTC, merged

2022-10-20 20:50 UTC, jcavar commented
Hey @groue, sorry, I am little slower.

Indeed, I've probably deleted the most useful part of the strict tables test.

Thanks for fixing it for me and thank you for your great work on this library!

2022-10-21 04:26 UTC, groue commented
You're welcome, and happy GRDB :-)